# Use an official OpenJDK runtime as a parent image
FROM openjdk:21-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the packaged jar file into the container
COPY target/*.jar app.jar

# Expose port 8080
EXPOSE 8099

# Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
